name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Unzip project
        run: unzip TomatoPro_Full_Project.zip -d extracted
      - name: Build debug APK
        uses: gradle/gradle-build-action@v2
        with:
          # Build the debug APK.  The project’s gradle.properties already sets a large
          # heap and metaspace for Gradle, so we don’t need to pass JVM args here.
          arguments: assembleDebug
          build-root-directory: extracted/TomatoPro
          # Specify a Gradle version since the project zip does not include a Gradle wrapper
          gradle-version: 8.3
          # Disable caching for Gradle to avoid cache save failures causing job failure.
          cache-disabled: true
      - name: Upload APK artifact
        # Use v4 of upload-artifact since v3 has been deprecated
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: extracted/TomatoPro/app/build/outputs/apk/debug/app-debug.apk
